import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from matplotlib.lines import Line2D
import matplotlib.markers as mmarkers
import matplotlib.colors as mcolors

df = pd.read_csv("data.csv")

# 1. Filter Data
metrics_to_plot = ["JaccardSimilarity", "AUC_PRC", "AUC_ROC"]
plot_df = df[
    (df["prc_threshold"] == True)
    & (df["time_type"] == "Real Time")
    & (df["metric"].isin(metrics_to_plot))
].copy()

# Sort and prepare combined labels
plot_df["metric"] = pd.Categorical(
    plot_df["metric"], categories=metrics_to_plot, ordered=True
)
plot_df = plot_df.sort_values(["metric", "dataset"])

plot_df["x_axis_group"] = (
    plot_df["dataset"].astype(str) + " | " + plot_df["metric"].astype(str)
)
group_order = list(dict.fromkeys(plot_df["x_axis_group"]))

# 2. Setup global method order and a unified custom palette
all_methods = list(plot_df["method"].unique())

custom_palette = {}
set2_colors = sns.color_palette("Set2", len(all_methods))
color_idx = 0

for m in all_methods:
    if m == "Correlation":
        custom_palette[m] = "#E63946"  # Red
    elif m == "Random":
        custom_palette[m] = "#457B9D"  # Blue
    else:
        custom_palette[m] = set2_colors[color_idx]
        color_idx += 1

# 3. Setup the Grid
g = sns.FacetGrid(
    plot_df,
    row="step_setting",
    height=4,
    aspect=1.8,
    margin_titles=True,
    sharex=True,
)


def single_swarm_modified(data, **kwargs):
    ax = plt.gca()

    # 1. Let Seaborn plot normally with default colors to handle the swarm math without crashing
    sns.swarmplot(
        data=data,
        x="x_axis_group",
        y="result",
        hue="method",
        order=group_order,
        size=4.5,
        dodge=False,
        ax=ax,
    )

    # Pre-calculate the custom marker paths
    path_diamond = (
        mmarkers.MarkerStyle("D")
        .get_path()
        .transformed(mmarkers.MarkerStyle("D").get_transform())
    )
    path_x = (
        mmarkers.MarkerStyle("X")
        .get_path()
        .transformed(mmarkers.MarkerStyle("X").get_transform())
    )

    # 2. Seaborn creates exactly one collection per method present in THIS specific grid pane.
    # They are created in the exact order of data["method"].unique().
    local_methods = data["method"].unique()

    # 3. Manually map the shapes, colors, and borders directly to the Matplotlib objects
    for collection, method in zip(ax.collections, local_methods):
        if method == "Correlation":
            collection.set_paths([path_diamond])
            collection.set_facecolors([mcolors.to_rgba("#E63946")])  # Red
            collection.set_edgecolors([(0, 0, 0, 1)])  # Black outline
            collection.set_linewidths([0.8])
            collection.set_sizes([40])

        elif method == "Random":
            collection.set_paths([path_x])
            collection.set_facecolors([mcolors.to_rgba("#457B9D")])  # Blue
            collection.set_edgecolors([(0, 0, 0, 1)])
            collection.set_linewidths([0.8])
            collection.set_sizes([45])

        else:
            # For standard methods, apply our consistent custom_palette colors
            if method in custom_palette:
                collection.set_facecolors([mcolors.to_rgba(custom_palette[method])])
            collection.set_edgecolors(["none"])
            collection.set_linewidths([0])

    # Clean up the automatic legend generated by the raw swarmplot
    if ax.get_legend():
        ax.get_legend().remove()


# Map the function
g.map_dataframe(single_swarm_modified)

# 5. Final Polish (Restored your exact formatting)
g.set(ylim=(0, 1.05))
g.set_axis_labels("", "Score (0.0 - 1.0)")

for ax in g.axes.flat:
    ax.set_xticks(range(len(group_order)))
    ax.set_xticklabels(group_order, rotation=90, ha="center", fontsize=7)

    # Visual separation between Dataset blocks
    for i in range(len(group_order)):
        if (i + 1) % len(metrics_to_plot) == 0:
            ax.axvline(i + 0.5, color="black", linestyle="-", alpha=0.1, linewidth=1)

# 6. Rebuild Legend to match new shapes
legend_elements = []

legend_elements.append(
    Line2D(
        [0],
        [0],
        marker="D",
        color="w",
        label="Correlation",
        markerfacecolor="#E63946",
        markeredgecolor="black",
        markersize=7,
    )
)
legend_elements.append(
    Line2D(
        [0],
        [0],
        marker="X",
        color="w",
        label="Random",
        markerfacecolor="#457B9D",
        markeredgecolor="black",
        markersize=7,
    )
)

other_methods = [m for m in all_methods if m not in ["Correlation", "Random"]]
for m in other_methods:
    legend_elements.append(
        Line2D(
            [0],
            [0],
            marker="o",
            color="w",
            label=m,
            markerfacecolor=custom_palette[m],
            markersize=5,
        )
    )

g.fig.legend(
    handles=legend_elements,
    loc="center right",
    bbox_to_anchor=(1.05, 0.5),
    title="Methods",
    fontsize="small",
)

# Final layout compression
plt.subplots_adjust(top=0.9, right=0.85, bottom=0.35, hspace=0.4)

plt.savefig("dot_plot_v2.svg", format="svg", bbox_inches="tight")
# plt.show()
