datasets:
  - tag: defaultArtista

method:
  name: ot_cfm
  train_and_test_script: ./methods/ot_cfm/train_and_test.sh
  metadata:
    method: 'prior'
    prior_method: 'basic_entropic_ot'
    reg: 0.9
    embedding_space: 'PCA'

metrics:
  - name: GraphSimMetric
    trajectory_infer_model:
      name: CellTypist
      renormalize: True
