##TODO
# 2026-02-04 16:26:28,575 | DEBUG | root | [warn] Ignoring unknown scIMF config parameter: auto_device
# 2026-02-04 16:26:28,575 | DEBUG | root | [warn] Ignoring unknown scIMF config parameter: cache_n_cells
# 2026-02-04 16:26:28,575 | DEBUG | root | [warn] Ignoring unknown scIMF config parameter: cuda_device
# 2026-02-04 16:26:28,575 | DEBUG | root | [warn] Ignoring unknown scIMF config parameter: leaveouts
# 2026-02-04 16:26:28,575 | DEBUG | root | [warn] Ignoring unknown scIMF config parameter: use_cuda

method:
  name: scIMF
  train_and_test_script: ./methods/scIMF/train_and_test.sh
  metadata:
    train_epochs: 200
    train_lr: 0.001
    train_batch: 512
    train_clip: 0.1
    save: 100
    seed: 0
    latent_dim: 50
    sinkhorn_blur: 0.1
    sinkhorn_scaling: 0.7
    lambda_marginal: 1.0
    use_intLoss: true
    use_cuda: true
    cuda_device: 1
    auto_device: true
    leaveouts: null
    dataset: AnnData
    cache_n_cells: 2000


metrics:
  # - name: OTLossMetric
 - name: GraphSimMetric
