datasets:
  - tag: defaultGarciaAlonso
  - tag: defaultGarciaAlonsoPseudotimeEvenCells
  - tag: defaultMa
  - tag: defaultMaPseudotimeEvenCells

method:
  name: WOT
  train_and_test_script: ./methods/WOT/train_and_test.sh

metrics:
 - name: GraphVisualization
 - name: OTLossMetric
 - name: GraphSimMetric
