method:
  name: Correlation
  metadata:
    correlation_method: pearsonr
    averaging_method: average
  train_and_test_script: ./methods/correlation/train_and_test.sh

metrics:
  - name: GraphSimMetric

metrics_skiplist:
  - name: StackedBarPlot
