datasets:
  - tag: defaultGarciaAlonsoPseudotimeEvenCells
  - tag: defaultSuoPseudotimeEvenCells

model:
  name: Cooccurrence
  train_and_test_script: ./models/cooccurrence/train_and_test.sh

metrics:
  - name: GraphSimMetric

metrics_skiplist:
  - name: StackedBarPlot
