dataset:
  name: SuoDataset
  data_path: ../data/suo/main.h5ad
  cell_lineage_file: ./examples/cell_lineages/b_cells/b_cell_line.txt
  cell_equivalence_file: ./examples/cell_lineages/b_cells/equal_names.txt
  preprocessed_dir: ../data/preprocessed/

model:
  name: ExampleRandomSampler
  train_and_test_script: ./examples/ExampleRandomSampler/train_and_test.sh

metrics:
 - L1Norm
 - GraphEditDistance
