datasets:
   - name: MaDataset
     data_path: ./data/ma/ma.h5ad
     # these filters need to be in order!
     filters:
      - name: LineageDatasetFilter
        cell_lineage_file: ./examples/cell_lineages/pancreas/trunk_lineage.txt
      - name: CopySplitFilter



model:
  name: MIOFlow
  train_and_test_script: ./models/MIOFlow/train_and_test.sh
  metadata:
    epochs: 1

metrics:
 - name: BaseMetric
