datasets:
  - tag: defaultGarciaAlonso
  - tag: defaultSuo

model:
  name: MIOFlow
  train_and_test_script: ./models/MIOFlow/train_and_test.sh
  metadata:
    epochs: 1

metrics:
 - name: L1Norm
 - name: GraphEditDistance
