datasets:
  - tag: defaultGarciaAlonso
  - tag: defaultSuo

model:
  name: PISDE
  train_and_test_script: ./models/PISDE/train_and_test.sh
  metadata:
    train_epochs: 1
    train_lr: 0.001
    train_lambda: 0.1
    train_batch: 0.1
    train_clip: 1.0
    save: 100
    sinkhorn_scaling: 0.7
    sinkhorn_blur: 0.1
    ns: 2000
    use_cuda: false
    device: 0
    seed: 0
    k_dims: "50,50"
    activation: tanh
    sigma_type: const
    sigma_const: 0.1
    start_t: 0
    leaveouts: null
    n_sim_cells: 2000


metrics:
 - name: GraphEditDistance
 - name: AverageShortestPathDiff
 - name: JaccardSimilarity
