datasets:
  - tag: EasyOlaniru
  - tag: MediumOlaniru
  - tag: HardOlaniru
model:
  name: PRESCIENT
  train_and_test_script: ./models/PRESCIENT/train_and_test.sh
  metadata:
    pretrain_epochs: 500
    train_epochs: 2000
    train_lr: 0.01
    train_dt: 0.1
    train_sd: 0.5
    train_tau: 1.0e-6
    train_batch: 0.1
    train_clip: 0.25
    save: 100
    pretrain: true
    train: true
    seed: 2
    gpu: 1
    weight: weight
    weight_name: null
    loss: euclidean
    k_dim: 500
    activation: softplus
    layers: 1
    num_neighbors_umap: 10
    # n_sim_cells: 2000
    epoch: best

metrics:
  #- name: GraphSimMetric
   - name: OTLossMetric
