# datasets:
#   - tag: defaultGarciaAlonso

model:
  name: scNODE
  train_and_test_script: ./models/scNODE/train_and_test.sh
  metadata:
    epochs: 1

metrics:
 - name: L1Norm
   trajectory_infer_model:
    name: kNN
    n_neighbors: 5
 - name: GraphEditDistance
