data_path: ../data/suo/main.h5ad
cell_lineage_file: ./examples/cell_lineages/b_cells/b_cell_line.txt
cell_equivalence_file: ./examples/cell_lineages/b_cells/equal_names.txt
model:
  name: scNODE
  train_script: scNODE_train.sh
  generate_script: scNODE_generate.sh
metrics:
 - L1Norm
