datasets:
  - name: GarciaAlonsoDataset
    data_path: ./data/garcia-alonso/human_germ.h5ad
    # these filters need to be in order!
    filters:
      - name: LineageDatasetFilter
        cell_lineage_file: ./examples/cell_lineages/germ/simple_cell_line.txt
      - name: CopySplitFilter

model:
  name: Squidiff
  train_and_test_script: ./models/Squidiff/train_and_test.sh
  metadata:
    epochs: 1

metrics:
 - name: GraphEditDistance
