model:
  name: scNODE
  train_and_test_script: ./models/scNODE/train_and_test.sh

metrics:
  - name: ClassifierMetrics
  - name: ClassifierMetrics
    trajectory_infer_model:
      name: Classifier
      model_classifier: True
